export const ENV_KEYS = {
  BOTPRESS_TOKEN: "VITE_BOTPRESS_TOKEN",
  BOTPRESS_BOT_ID: "VITE_BOTPRESS_BOT_ID",
  BOTPRESS_WORKSPACE_ID: "VITE_BOTPRESS_WORKSPACE_ID",
  ADMIN_EMAIL: "VITE_ADMIN_EMAIL",
  MASTER_PASSWORD: "VITE_MASTER_PASSWORD",
};
