name: Deploy React App with Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, react-app-runner]
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the React App
      - name: Build React App
        run: npm run build

      # Step 5: Deploy (Customize for Your Environment)
      - name: Deploy to Server
        run: |
          sudo mkdir -p /var/www/react-app
          sudo cp -R dist/* /var/www/react-app
        env:
          DEPLOY_PATH: /var/www/react-app # Example deployment directory


      # # Optional: Cleanup Node Modules (if needed)
      # - name: Cleanup Node Modules
      #   run: rm -rf node_modules
